export const collections = [
  {
    id: 5,
    name: "Serum Trị Nám",
    price: 580000,
    discount: 20,
    shortDescription: "shortDescription",
    madeIn: "Hàn Quốc",
    type: "Skincare",
    image: "../../src/assets/images/serumtrinam1.JPG",
    sizes: ["30ml"],

  },
  {
    id: 2,
    name: "Serum Collagen Chống lão hoá",
    price: 530000,
    discount: 15,
    shortDescription: "shortDescription",
    madeIn: "Hàn Quốc",
    type: "Skincare",
    image: "../../src/assets/images/serumColagen2.JPG",
    sizes: ["30ml"],
  },
  {
    id: 3,
    name: "Serum Phục hồi da",
    price: 540000,
    discount: 15,
    shortDescription: "shortDescription",
    madeIn: "Hàn Quốc",
    type: "Skincare",
    image: "../../src/assets/images/serumphuchoida2.JPG",
    sizes: ["30ml"],
  },
  {
    id: 4,
    name: "Serum Trị mụn",
    price: 560000,
    discount: 15,
    shortDescription: "shortDescription",
    madeIn: "Hàn Quốc",
    type: "Skincare",
    image: "../../src/assets/images/serumtrimun2.JPG",
    sizes: ["30ml"],
  }
];
