export const specialProducts = [
  {
    id: 1,
    name: "Nước hoa hồng",
    price: 550000,
    discount: 15,
    shortDescription: "shortDescription",
    madeIn: "Hàn Quốc",
    type: "Skincare",
    image: "../../src/assets/images/nuochoahong1.JPG",
    thanhphan: "Thành phần chính Thành phần chính",
    sizes: ["120ml"],
  },
  {
    id: 2,
    name: "Serum Collagen Chống lão hoá",
    price: 530000,
    discount: 15,
    shortDescription: "shortDescription",
    madeIn: "Hàn Quốc",
    type: "Skincare",
    image: "../../src/assets/images/serumColagen1.JPG",
    thanhphan: "Thành phần chính Thành phần chính",
    sizes: ["30ml"],
  },
  {
    id: 3,
    name: "Serum Phục hồi da",
    price: 540000,
    discount: 15,
    shortDescription: "shortDescription",
    madeIn: "Hàn Quốc",
    type: "Skincare",
    image: "../../src/assets/images/serumphuchoida1.JPG",
    thanhphan: "Thành phần chính Thành phần chính",
    sizes: ["30ml"],
  },
  {
    id: 4,
    name: "Serum Trị mụn",
    price: 560000,
    discount: 15,
    shortDescription: "shortDescription",
    madeIn: "Hàn Quốc",
    type: "Skincare",
    image: "../../src/assets/images/serumtrimun1.JPG",
    thanhphan: "Thành phần chính Thành phần chính",
    sizes: ["30ml"],
  },
  {
    id: 5,
    name: "Serum Trị Nám",
    price: 580000,
    discount: 20,
    shortDescription: "shortDescription",
    madeIn: "Hàn Quốc",
    type: "Skincare",
    image: "../../src/assets/images/serumtrinam1.JPG",
    thanhphan: "Thành phần chính Thành phần chính",
    sizes: ["30ml"],
  },
  {
    id: 6,
    name: "Kem dưỡng",
    price: 550000,
    discount: 15,
    shortDescription: "shortDescription",
    madeIn: "Hàn Quốc",
    type: "Skincare",
    image: "../../src/assets/images/kemduong1.JPG",
    thanhphan: "Thành phần chính Thành phần chính",
    sizes: ["50ml"],
  },
];
