export const specialProducts = [
  {
    id: 1,
    name: "Kem Dưỡng Body Trẻ Hóa Da Toàn Thân Image BODY SPA Rejuvenating Body Lotion",
    price: 1190000,
    discount: 15,
    shortDescription: "shortDescription",
    image: "../src/assets/images/demo.webp",
    sizes: ["170g", "450g"],
  },
  {
    id: 2,
    name: "Kem Dưỡng Body Trẻ Hóa Da Toàn Thân Image BODY SPA Rejuvenating Body Lotion",
    price: 1190000,
    discount: 15,
    shortDescription: "shortDescription",
    image: "../src/assets/images/demo.webp",
    sizes: ["170g", "450g"],
  },
  {
    id: 3,
    name: "Kem Dưỡng Body Trẻ Hóa Da Toàn Thân Image BODY SPA Rejuvenating Body Lotion",
    price: 1190000,
    discount: 15,
    shortDescription: "shortDescription",
    image: "../src/assets/images/demo.webp",
    sizes: ["170g", "450g"],
  },
  {
    id: 4,
    name: "Kem Dưỡng Body Trẻ Hóa Da Toàn Thân Image BODY SPA Rejuvenating Body Lotion",
    price: 1190000,
    discount: 15,
    shortDescription: "shortDescription",
    image: "../src/assets/images/demo.webp",
    sizes: ["170g", "450g"],
  },
];
