export const specialProducts = [
  {
    id: 1,
    name: "Kem Dưỡng Body Trẻ Hóa Da Toàn Thân Image BODY SPA Rejuvenating Body Lotion",
    price: 1190000,
    discount: 15,
    shortDescription: "shortDescription",
    image: "../../public/prd_1.jpg",
    sizes: ["170g", "450g"],
  },
  {
    id: 2,
    name: "Kem Dưỡng Body Trẻ Hóa Da Toàn Thân Image BODY SPA Rejuvenating Body Lotion",
    price: 1190000,
    discount: 15,
    shortDescription: "shortDescription",
    image: "../../public/prd_3.jpg",
    sizes: ["170g", "450g"],
  },
  {
    id: 3,
    name: "Kem Dưỡng Body Trẻ Hóa Da Toàn Thân Image BODY SPA Rejuvenating Body Lotion",
    price: 1190000,
    discount: 15,
    shortDescription: "shortDescription",
    image: "../../public/prd_4.jpg",
    sizes: ["170g", "450g"],
  },
  {
    id: 4,
    name: "Kem Dưỡng Body Trẻ Hóa Da Toàn Thân Image BODY SPA Rejuvenating Body Lotion",
    price: 1190000,
    discount: 15,
    shortDescription: "shortDescription",
    image: "../../public/prd_5.jpg",
    sizes: ["170g", "450g"],
  },
];
